### ISSUE TITLE
Research Database options for what the app requirements needs.

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#1]

**Comment by coultergeist** [comment]
Looks like the most common db options out there for React is Firebase, MongoDB and PostgreSQL. It looks like PostgreSQL might be a little more intuitive (while Firebase is the quickest and easiest setup option) with more advanced manipulation techniques and expandability for large data sets...not really one of our concerns for this project at the moment. We're going with Firebase but if you were interested in learning more about PostgreSQL here is [an article about React dbs](https://www.quora.com/What-is-the-best-database-to-use-with-ReactJS) that I liked if you want to learn more.
