### ISSUE TITLE
Create a Client profile landing page

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#13]
Rough screen for when a Client logs in. Can focus on function and framework with very little styling at the moment. Look at wireframes for the look of the screen/profile.

**Comment by ZakBrinlee** [comment]
Created this. Used a mock UI I found online. Will be pushed with my code tonight once I clean it up.

**Comment by coultergeist** [comment]
Finished by Zak.
![screenshot_20181028-164014_expo](https://user-images.githubusercontent.com/16545169/47690926-4cda4c00-dbad-11e8-89d6-8c45ef7737c9.jpg)
