### ISSUE TITLE
Work on Firebase Authentication with dual access/profile indicators

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#15]
Currently running auth using Firebase Authentication. Need to determine a way to split the authentication by access/profiles since there is a Stylist and Client profiles.

**Comment by coultergeist** [comment]
Zak found this tutorial as a great lead for [dual profiles](https://www.youtube.com/watch?v=3hj_r_N0qMs)

Here is a general overview of [minting custom tokens](https://www.youtube.com/watch?v=WtYzHTXHBp0)

**Comment by ZakBrinlee** [comment]
Got this to work and can pull the user role from either AsyncStorage or the DB. Will be doing to push to the branch and merge request tonight once I clean up my code

**Comment by ZakBrinlee** [comment]
This is done. All except the split navigation. Will open a new issue for that and work on it this week and ask Brenden to look at it.
