### ISSUE TITLE
Style 'Signup' page

### ISSUE THREAD

**Issue by coultergeist** [ZakBrinlee/Project-8#16]
Style the landing page where stylists/clients will use when first creating an account.

**Comment by coultergeist** [comment]
Zak found a [great tutorial](https://reactnativeexample.com/switch-selector-to-react-native/) to get the page up and running that features a "Client" and "Stylist" slider button option.

**Comment by ZakBrinlee** [comment]
This was completed by Yitong in issue #10. Closing this duplicate issue
