### ISSUE TITLE
Research developing the messaging feature of app

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#2]

**Comment by ZakBrinlee** [comment]
Tyler when you get a chance please provide and update on this issue.

**Comment by TyReed12** [comment]
Using this tutorial as a guide:
https://blog.expo.io/how-to-build-a-chat-app-with-react-native-3ef8604ebb3c

Unfortunately I'm still having that network request error when trying to run the app on expo on my phone, I'm going to try and get some help after class tomorrow (10/14).

**Comment by TyReed12** [comment]
Done researching.
