### ISSUE TITLE
Setup Firebase for Messenging

### ISSUE THREAD

**Issue by TyReed12** [ZakBrinlee/Project-8#20]

**Comment by coultergeist** [comment]
Tyler, I'm using [this tutorial](https://firebase.google.com/docs/database/ios/structure-data) for Firebase dataset manipulation and thought it might help us approach the chat feature. Hope it helps!

**Comment by ZakBrinlee** [comment]
This issue is no longer needed. This has been completed and implemented with the merge from SendBirdChat branch.
