### ISSUE TITLE
Create "Edit Profile" landing area (builds on #32)

### ISSUE THREAD

**Issue by coultergeist** [ZakBrinlee/Project-8#33]
Create the page to modify profile info. After the function is created and placed (when #32 closes) then begin creating this page.

**Comment by ZakBrinlee** [comment]
Adding Yitong to help with this feature

**Comment by coultergeist** [comment]
This is area "Edit Profile" now exists (via Zak and Tyler). Hoping to enable this feature before launch/final presentation.
