### ISSUE TITLE
Create StyleMemo Form

### ISSUE THREAD

**Issue by coultergeist** [ZakBrinlee/Project-8#42]
Create a "form" that details any information a client may want to share with their stylist. We'll see how much of this I can do. This will be a form with radio buttons with an image upload feature that connects to the chat feature.

See the doc [here](https://docs.google.com/document/d/1JS-EONICvfyFa_E3OY3YR3HBRU0ychCoMfb1Td0HIb8/edit).

styleMemo: Hair
 
	▪Date of my last haircut:           
	▪Date of my last color or chemical service:          
Haircut
My Current Length: 🤳🏻(snap & send a selfie)
	▪Long
	▪Medium
	▪Short
My Desired Length:  (upload a photo)
	▪Long
	▪Medium
	▪Short
	▪I would like recommendations
My Hair Texture:	
	▪Straight
	▪Wavy
	▪Curly
	▪Frizzy
	▪Kinky
My Hair Density:
	▪Type I: Thin
	▪Type II: Medium
	▪Type III: Coarse
Color 
My Current Hair Color:  🤳🏻(snap & send a selfie)
	▪Blonde
	▪Brown
	▪Black
	▪Red
	▪Grey
My Desired Hair Color:   (upload a photo)
	▪Blonde
	▪Brown
	▪Black
	▪Red
	▪Grey
	▪I would like recommendations
Dye Color & Chemical Services History: 
Click yes if any of the following apply: ***It’s important to be transparent when answering for the best results.
	▪0-6 months: I have dyed colored and/or highlighted my hair at home with box dye or bleach
	▪0-6 months: A professional has dyed colored and/or highlighted my hair
	▪0-6 months: My hair has been bleached
	▪0-6 months: My hair has been permed
	▪0-6 months: A professional has give me a keratin smoothing treatment, Brazilian blowout, or Relaxer
Important things to know about my hair:
	▪I have a lot of hair but my hair texture is fine
	▪My hair is frizzy regardless of the time I spend styling
	▪My hair holds when its professionally styled (ie: curling, straightening, set, etc)
	▪My hair does NOT respond to styling regardless of who styles it
Important things to know about me: 
	▪I am busy, I prefer to be in and out of salon
	▪I like to relax when I’m in the salon and slow down
	▪I’m a chair hopper, even when I find a stylist I like
	▪I’ve never found a stylist who gets me
	▪I miss my old stylist, nobody styles like him/her
	▪I’m loyal to great stylists

**Comment by coultergeist** [comment]
Using [this tutorial ](https://www.npmjs.com/package/react-native-radio-buttons-group)

**Comment by coultergeist** [comment]
Tutorials I need for future reference:
Text styling[https://facebook.github.io/react-native/docs/text](url)
[React Native Elements](https://react-native-training.github.io/react-native-elements/)
Tile[https://react-native-training.github.io/react-native-elements/docs/0.19.1/tile.html](url)
Multi/slot machine/scroll picker[http://www.reactnative.com/picking-the-right-component-for-react-native/](url)

**Comment by ZakBrinlee** [comment]
Danielle

- Forms are no longer supported for React Native Elements. 
I couldn't figure out how to get checkbox groups to work. I did find ButtonGroup that seems simpler and added it in for you to check out. 

I wouldn't focus on styling as much as function.  Hope it helps.

**Comment by coultergeist** [comment]
This page of the app has been created despite the unavoidable issues we're having with forms. Closed.
