### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#43]
Final Presentation and App Walkthrough.

Planning to meet Sunday, December 9th.

**Comment by coultergeist** [comment]
Created and the slides can be found [here](https://docs.google.com/presentation/d/1pPHks-s_IwPfomOQqCiEFXHf1gfZH2QbTOUoIs3CQ84/edit?usp=sharing). This issue is complete and closed.
