### ISSUE TITLE
Keyboard will push up screen feature

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#46]
On every screen when you input text it does not automatically push the screen up so you can see the field you are typing. 

Found this tutorial when I searched for RN keyboard aware scroll view. 

https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580

**Comment by TyReed12** [comment]
Done. Submitted pull request.

**Comment by ZakBrinlee** [comment]
Reviewed and merged branch. Well done
