### ISSUE TITLE
Create Statement of Work

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#5]
As a team, you should now write a SOW that accurately captures the high-level details of the project.

You can use this template as a starting point and modify as appropriate.

Because this is a learning exercise, formal client approval for the SOW isn't required, as it would be in a normal commercial project. But you should confirm it's accuracy with your client.

Google doc of Project 8 Statement of Work: 
https://docs.google.com/document/d/1igMa8YXmzbbb1xhnbabFUe5xpdFsa1k8ImHy9Noytf4/edit?usp=sharing

**Comment by coultergeist** [comment]
I am starting work on this today. I've created one before so I think I can breeze through this. Will update when complete for feedback to confirm I've captured the objectives.

**Comment by coultergeist** [comment]
Finished the first draft of the SOW. Here's the Drive [link to the Word Doc ](https://docs.google.com/document/d/1mY-MXXaqXjf7jwe6bhcTwUAMUWgxVzHE0EvKwlUlRWI/edit?usp=sharing)and another [link for the PDF](https://drive.google.com/drive/u/1/folders/10j_HnZCTFUVmPs3Xl8w9gdg7HxpTpwpA) (I assume we'll just publish the PDF once it's signed).

**Comment by ZakBrinlee** [comment]
Awesome job submitted for the assignment. Closing issue.
