### ISSUE TITLE
User authentication - feature

### ISSUE THREAD

**Issue by ZakBrinlee** [ZakBrinlee/Project-8#8]
Create user authentication code that will validate users access using Firebase Authentication

**Comment by ZakBrinlee** [comment]
Danielle and I are currently working on this feature primarily using this tutorial: https://medium.com/react-native-training/react-native-firebase-authentication-7652e1d2c8a2

**Comment by coultergeist** [comment]
We're going to try to implement both login features as an added bonus to the client. 

Zak is researching email/password authentication technique.
Danielle is researching "Federated identity" auth which allows for Google/FB/Twitter connection. See this tutorial [](https://firebase.google.com/docs/auth/)

**Comment by ZakBrinlee** [comment]
Got the app working with authentication using Firebase. The code is pushed onto the master branch. Please see readme for instructions on cloning repo. From here we can work on Federated authentication in addition of password/email.

**Comment by ZakBrinlee** [comment]
Got this working so closing issue. Will be opening others regarding additional auth features.
